language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      addons:
       apt:
         packages:
           - build-essential
           - cmake
           - ocl-icd-opencl-dev
           - fglrx  # amd catalyst, needed for ADL
           - libuv-dev
           - libmicrohttpd-dev

script:
     - sh build.sh
